#!/usr/bin/env python
import ropgenerator.ROPGenerator as ROP
import sys

debug_time = False
if( len(sys.argv) == 2 ):
    if( sys.argv[1] == "-debug-time"):
        debug_time = True
        
ROP.main(debug_time)

